# Generated by Django 4.2.19 on 2025-02-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='razorpay_order_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='payment_status',
            new_name='event_payment_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='razorpay_payment_id',
            new_name='event_razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='razorpay_signature',
            new_name='event_razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='total_fee',
            new_name='event_total_fee',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='workshop',
        ),
        migrations.AddField(
            model_name='user',
            name='event_razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
