# Generated by Django 4.2.19 on 2025-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_user_branch_user_dob_user_encurso_id_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_team', models.BooleanField(default=False)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
