# Generated by Django 4.2.19 on 2025-02-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='layout',
            field=models.CharField(blank=True, choices=[('cktlayout', 'Ckt Layout'), ('pplayout', 'PP Layout'), ('hackathonlayout', 'Hachathon Layout'), ('quizzlayout', 'Quizz Layout'), ('projectlayout', 'Project Layout'), ('photolayout', 'Photo Layout')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='layout',
            field=models.CharField(blank=True, choices=[('evlayout', 'EV Layout'), ('iotlayout', 'IoT Layout'), ('matlablayout', 'MATLAB Layout'), ('dronelayout', 'Drone Layout')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='timing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
