# Generated by Django 4.2.19 on 2025-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_user_home_town_user_institute_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.AddField(
            model_name='teammember',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='members',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='workshop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
