# Generated by Django 4.2.19 on 2025-03-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_event_members_workshop_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_members',
            old_name='workshop',
            new_name='event',
        ),
    ]
